import type { Dict, IMutateCtx, IInnerSetStateOptions } from '../../types/base';
import type { TInternal } from './buildInternal';
import { execDepFns } from './notify';

export interface ICommitStateOptions extends IInnerSetStateOptions {
  state: Dict;
  internal: TInternal;
  mutateCtx: IMutateCtx;
  forAtom: boolean;
  sn: number;
  desc?: any;
}

// 此文件存在过强制干预依赖项的 interveneDeps 逻辑，在 execDepFns 执行，但考虑此功能无用已移除

export function commitState(opts: ICommitStateOptions) {
  const { state, internal } = opts;
  const { rawState, isDeep, ver, snap } = internal;

  if (isDeep) {
    internal.prevSnap = ver === 0 ? { ...snap } : snap;
    // now state is a structural shared obj generated by limu
    internal.snap = state;
    Object.assign(rawState, state);
  } else {
    internal.snap = { ...rawState };
  }

  internal.ver += 1;
  internal.sn = opts.sn;
  execDepFns(opts);
}
